feat: 测试vllm test

diff --git a/.github/workflows/_e2e_test.yaml b/.github/workflows/_e2e_test.yaml
--- a/.github/workflows/_e2e_test.yaml
+++ b/.github/workflows/_e2e_test.yaml
@@ -63,8 +63,8 @@ jobs:
           npu-smi info
           cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info
           ls -la packages.txt || echo "packages.txt NOT FOUND"
-          ls -la .github/workflows/_e2e_test_optimized.yaml || echo "_e2e_test_optimized.yaml NOT FOUND"
-          echo "Hash is: ${{ hashFiles('packages.txt', '.github/workflows/_e2e_test_optimized.yaml') }}"
+          ls -la .github/workflows/_e2e_test.yaml || echo "_e2e_test.yaml NOT FOUND"
+          echo "Hash is: ${{ hashFiles('packages.txt', '.github/workflows/_e2e_test.yaml') }}"
       # Step 1: Cache apt packages with OBS
       - name: Cache apt packages with OBS
         uses: runs-on/cache@v4
