feat: 测试vllm test

diff --git a/.github/workflows/_e2e_test.yaml b/.github/workflows/_e2e_test.yaml
--- a/.github/workflows/_e2e_test.yaml
+++ b/.github/workflows/_e2e_test.yaml
@@ -3,12 +3,6 @@ name: 'e2e test'
 on:
   workflow_call:
     secrets:
-      HW_OBS_AK:
-        required: true  # 声明该密钥为必填
-        description: "Huawei OBS Access Key"
-      HW_OBS_SK:
-        required: true
-        description: "Huawei OBS Secret Key"
       HW_REDIS_PWD:
         required: true
         description: "Huawei redis password"
@@ -36,8 +30,6 @@ env:
   UV_PYTHON_DOWNLOADS: never
   UV_SYSTEM_PYTHON: 1
 
-  AWS_ACCESS_KEY_ID: ${{ secrets.HW_OBS_AK }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_OBS_SK }}
   SCCACHE_BUCKET: obs-guiiyang1-ascend-test
   SCCACHE_ENDPOINT: https://obs.cn-southwest-2.myhuaweicloud.com
   SCCACHE_REGION: cn-southwest-2
@@ -77,7 +69,6 @@ jobs:
           pip install uv
           #uv venv
           uv pip install --system sccache
-          sccache -s
 
       - name: Check npu and CANN info
         run: |
@@ -91,6 +82,18 @@ jobs:
           DIR_HASH=$(find ./csrc -type f -not -path '*/.*' | sort | xargs sha256sum | sha256sum | awk '{print $1}')
           echo "DIR_HASH=$DIR_HASH" >> $GITHUB_OUTPUT
           echo "hash: $DIR_HASH"
+      - name: Load OBS credentials from file
+        run: |
+          sleep 300
+          INI_FILE="/root/.cache/obstest.ini"
+          if [ -f "$INI_FILE" ]; then
+            HW_OBS_AK=$(grep '^HW_OBS_AK=' "$INI_FILE" | cut -d'=' -f2-)
+            HW_OBS_SECRET=$(grep '^HW_OBS_SECRET=' "$INI_FILE" | cut -d'=' -f2-)
+            echo "AWS_ACCESS_KEY_ID=$HW_OBS_AK" >> $GITHUB_ENV
+            echo "AWS_SECRET_ACCESS_KEY=$HW_OBS_SECRET" >> $GITHUB_ENV
+          else
+            echo "Error: $INI_FILE not found" && exit 1
+          fi
       - name: Cache dependencies
         uses: runs-on/cache@v4
         with:
@@ -103,8 +106,6 @@ jobs:
           # 👇 指定你的 OBS bucket（必须用 virtual-hosted 域名！）
           RUNS_ON_S3_BUCKET_CACHE: obs-guiiyang1-ascend-test
           RUNS_ON_S3_BUCKET_ENDPOINT: https://obs.cn-southwest-2.myhuaweicloud.com
-          AWS_ACCESS_KEY_ID: ${{ secrets.HW_OBS_AK }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_OBS_SK }}
           AWS_REGION: cn-southwest-2
 #      - name: Cache dependencies
 #        uses: runs-on/cache@v4
